stages:
  - build

variables:
  DEPENDENCIES: cmake gcc glib2-devel gnutls-devel meson ninja-build
  CPPCHECK_OPTIONS: "--enable=warning --enable=style --enable=performance --enable=portability --std=c99 --template='{id}:{file}:{line},{severity},{message}'"

fedora:Werror:
  image: fedora:latest
  stage: build
  before_script:
    - dnf upgrade -y
    - dnf install -y 'dnf-command(builddep)'
    - dnf install -y $DEPENDENCIES
  script:
    - meson _build -Dwerror=true
    - meson compile -C _build
  artifacts:
    when: on_failure
    paths:
      - _build/meson-logs/meson-log.txt

fedora:static-analyzers:
  image: fedora:latest
  stage: build
  before_script:
    - dnf upgrade -y
    - dnf install -y 'dnf-command(builddep)'
    - dnf install -y $DEPENDENCIES clang-analyzer cppcheck
  script:
    - meson _build
    - meson compile -C _build --ninja-args scan-build
    - cppcheck --force -q $CPPCHECK_OPTIONS .
  artifacts:
    when: on_failure
    paths:
      - _build/meson-logs/meson-log.txt
